name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and build frontend
        run: |
          echo "=== Install frontend ==="
          cd client
          npm install
          npm run build
          echo "=== Done build frontend ==="

      - name: Install backend dependencies
        run: |
          echo "=== Install backend ==="
          npm install
          echo "=== Done backend install ==="

      - name: Deploy to EC2 via SSH using Docker
        env:
          PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem

          echo "--- Connecting EC2 ---"
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.239.37.52 "mkdir -p /home/ubuntu/node-vue-ele-app"

          echo "--- Start SCP (Docker project) ---"
          scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yml ubuntu@13.239.37.52:/home/ubuntu/node-vue-ele-app
          echo "--- compose SCP (Docker project) ---"

          scp -o StrictHostKeyChecking=no -i key.pem -r client/dist ubuntu@13.239.37.52:/home/ubuntu/node-vue-ele-app
          echo "--- client SCP (Docker project) ---"

          scp -o StrictHostKeyChecking=no -i key.pem Dockerfile server.js package.json package-lock.json ubuntu@13.239.37.52:/home/ubuntu/node-vue-ele-app
          echo "--- server files SCP (Docker project) ---"

          scp -o StrictHostKeyChecking=no -i key.pem -r config models "routes/api" ubuntu@13.239.37.52:/home/ubuntu/node-vue-ele-app
          echo "--- backend folders SCP (Docker project) ---"

          echo "--- Start SSH commands (Docker Compose) ---"
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.239.37.52 << 'EOF'
            sudo apt update && sudo apt install -y tmux
            cd /home/ubuntu/node-vue-ele-app
            echo "使用 tmux 開始部署"
            tmux new-session -d -s deploy_session 'docker compose down && docker compose build && docker compose up -d'
            echo "tmux 中啟動 Docker 完成"
          EOF